"""empty message

Revision ID: 098608655f0c
Revises:
Create Date: 2025-06-10 16:46:22.056305

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "098608655f0c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "persona",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nick_name", sa.String(length=250), nullable=True),
        sa.Column("nombre", sa.String(length=250), nullable=True),
        sa.Column("apellido", sa.String(length=250), nullable=True),
        sa.Column("email", sa.String(length=250), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("persona")
    # ### end Alembic commands ###
